# Generated by Django 3.0.8 on 2020-08-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapi', '0002_searchapi_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchapi',
            name='product_search_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
